#!/bin/bash
echo -n "Enter Fingerprint: "
read finger
echo -n "Enter Token: "
read token
echo provider '"digitalocean"' { >> vps1.tf
  echo token = '"'$token'"'}  >> vps1.tf
echo resource '"digitalocean_tag" "foobar"' { >> vps1.tf
echo   name = '"raidon35"'}  >> vps1.tf
echo  resource '"digitalocean_droplet" "web" '{  >> vps1.tf
  echo   image  = '"ubuntu-18-04-x64"' >> vps1.tf
 echo  name   = '"RavshanYuldashev"' >> vps1.tf
 echo  region = '"nyc1" ' >> vps1.tf
 echo size   = '"s-1vcpu-1gb" ' >> vps1.tf
echo ssh_keys = ['"'$finger'"']} >> vps1.tf
terraform init
terraform apply

